[build]
# Railway will use Node.js environment
builder = "NIXPACKS"

# Install dependencies inside backend folder
buildCommand = "cd backend && npm install"

[start]
# Start your backend from backend folder
command = "cd backend && npm run start"

[deploy]
# Run migrations or other setup commands if needed
startCommand = "cd backend && npm run start"
